- name: overwrite nginx config
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - restart nginx

- name: install required package
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: /var/lib/awx/venv/ansible
  with_items:
    - awscli
    - boto3
    - ansible-tower-cli

- name: fix log files owner
  shell: "chown {{ aw_user }}:{{ aw_group }} /var/log/tower/*"
  notify:
    - restart supervisor

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- set_fact:
    tower_settings:
      AWX_PROOT_SHOW_PATHS: "{{ tvlk_google_oauth_key }}"
      DEFAULT_JOB_TIMEOUT: "{{ tvlk_tower_job_execution_timeout }}"
      DEFAULT_INVENTORY_UPDATE_TIMEOUT: "{{ tvlk_tower_inventory_update_timeout }}"
      DEFAULT_PROJECT_UPDATE_TIMEOUT: "{{ tvlk_tower_project_update_timeout }}"
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "{{ tvlk_google_oauth_key }}"
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "{{ tvlk_google_oauth_secret }}"
      SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS: ['traveloka.com']
      SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS: { hd: 'traveloka.com' }
      SOCIAL_AUTH_GOOGLE_OAUTH2_ORGANIZATION_MAP:
        'Traveloka':
          users: true
  when: tvlk_google_oauth_key is defined and tvlk_google_oauth_secret is defined

- name: configure google oauth
  uri:
    url: http://localhost/api/v1/settings/google-oauth2/
    method: PATCH
    user: admin
    password: "{{ admin_password }}"
    body: "{{ tower_settings | to_json }}"
    force_basic_auth: yes
    body_format: json
  when: tower_settings is defined and inventory_hostname == groups['tower'][0]

